In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import *
import random
from collections import defaultdict, Counter

In [2]:
df = pd.read_csv('iris.csv', header = None).as_matrix()

In [3]:
data = load_iris()

In [4]:
x = data.data
y = data.target

In [5]:
minimum = min(x.flatten())
maximum = max(x.flatten())

population = np.arange(minimum, maximum, 0.1)

In [6]:
centroid = random.sample(list(x), 10)

In [7]:
centroid

[array([6.1, 2.6, 5.6, 1.4]),
 array([4.4, 2.9, 1.4, 0.2]),
 array([5.4, 3. , 4.5, 1.5]),
 array([5.7, 2.9, 4.2, 1.3]),
 array([5.7, 2.8, 4.1, 1.3]),
 array([5.4, 3.4, 1.5, 0.4]),
 array([5.8, 2.7, 5.1, 1.9]),
 array([6. , 2.2, 4. , 1. ]),
 array([7.4, 2.8, 6.1, 1.9]),
 array([7.7, 2.6, 6.9, 2.3])]

In [8]:
euc_distance = [np.linalg.norm(i-j) for i in x for j in centroid]

In [152]:
d = dict()
d2= dict()

for i in x:
    for index, j in enumerate(centroid):
        d[index] = np.linalg.norm(i-j)
        d2[index] = j
        i = d2[min(d, key = d.get)]
        print(i)
      


[6.1 2.6 5.6 1.4]
[6.1 2.6 5.6 1.4]
[5.4 3.  4.5 1.5]
[5.7 2.9 4.2 1.3]
[5.7 2.8 4.1 1.3]
[5.7 2.8 4.1 1.3]
[5.7 2.8 4.1 1.3]
[5.7 2.8 4.1 1.3]
[5.7 2.8 4.1 1.3]
[5.7 2.8 4.1 1.3]
[5.7 2.8 4.1 1.3]
[5.7 2.8 4.1 1.3]
[5.7 2.8 4.1 1.3]
[5.7 2.9 4.2 1.3]
[5.7 2.9 4.2 1.3]
[5.7 2.9 4.2 1.3]
[5.7 2.9 4.2 1.3]
[5.7 2.9 4.2 1.3]
[5.7 2.9 4.2 1.3]
[5.7 2.9 4.2 1.3]
[5.7 2.9 4.2 1.3]
[5.7 2.9 4.2 1.3]
[5.7 2.9 4.2 1.3]
[5.7 2.9 4.2 1.3]
[5.7 2.9 4.2 1.3]
[5.7 2.9 4.2 1.3]
[5.7 2.9 4.2 1.3]
[5.7 2.9 4.2 1.3]
[5.7 2.9 4.2 1.3]
[5.7 2.9 4.2 1.3]
[5.7 2.9 4.2 1.3]
[5.7 2.9 4.2 1.3]
[5.7 2.9 4.2 1.3]
[5.7 2.9 4.2 1.3]
[5.7 2.9 4.2 1.3]
[5.7 2.9 4.2 1.3]
[5.7 2.9 4.2 1.3]
[5.7 2.9 4.2 1.3]
[5.7 2.9 4.2 1.3]
[5.7 2.9 4.2 1.3]
[5.7 2.9 4.2 1.3]
[5.7 2.9 4.2 1.3]
[5.7 2.9 4.2 1.3]
[5.7 2.9 4.2 1.3]
[5.7 2.9 4.2 1.3]
[5.7 2.9 4.2 1.3]
[5.7 2.9 4.2 1.3]
[5.7 2.9 4.2 1.3]
[5.7 2.9 4.2 1.3]
[5.7 2.9 4.2 1.3]
[5.7 2.9 4.2 1.3]
[5.7 2.9 4.2 1.3]
[5.7 2.9 4.2 1.3]
[5.7 2.9 4.2 1.3]
[5.7 2.9 4.2 1.3]
[5.7 2.9 4

In [131]:
d2

{0: array([6.1, 2.6, 5.6, 1.4]),
 1: array([4.4, 2.9, 1.4, 0.2]),
 2: array([5.4, 3. , 4.5, 1.5]),
 3: array([5.7, 2.9, 4.2, 1.3]),
 4: array([5.7, 2.8, 4.1, 1.3]),
 5: array([5.4, 3.4, 1.5, 0.4]),
 6: array([5.8, 2.7, 5.1, 1.9]),
 7: array([6. , 2.2, 4. , 1. ]),
 8: array([7.4, 2.8, 6.1, 1.9]),
 9: array([7.7, 2.6, 6.9, 2.3])}

In [79]:
min(e)

0.3872983346207423