In [1]:
from sklearn.naive_bayes import MultinomialNB
import pandas as pd
import numpy as np


In [17]:
data = pd.read_csv('spambase.csv').as_matrix()

In [18]:
np.random.shuffle(data)

In [19]:
print(data)

[[0.00e+00 0.00e+00 0.00e+00 ... 5.00e+00 7.90e+01 0.00e+00]
 [0.00e+00 1.70e-01 0.00e+00 ... 1.40e+01 2.37e+02 0.00e+00]
 [7.80e-01 0.00e+00 7.80e-01 ... 2.20e+01 1.15e+02 1.00e+00]
 ...
 [0.00e+00 0.00e+00 0.00e+00 ... 2.30e+01 7.90e+01 1.00e+00]
 [0.00e+00 0.00e+00 0.00e+00 ... 5.00e+00 5.50e+01 0.00e+00]
 [0.00e+00 0.00e+00 0.00e+00 ... 1.60e+01 7.20e+01 1.00e+00]]


In [20]:
X = data[:,:48]
Y = data[:,-1]

In [21]:
x_train = X[:-100, ]
y_train = Y[:-100, ]
x_test = X[:,-100]

In [31]:
df2 = pd.read_csv('csv/Brown University Copy.csv').as_matrix()